# Generated by Django 3.2.8 on 2021-11-08 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('art_image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('trade_date', models.DateField()),
                ('material', models.CharField(max_length=32)),
                ('size', models.CharField(max_length=32)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.artist')),
            ],
        ),
    ]
