# Generated by Django 3.2.8 on 2021-11-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='board/image/%Y/%m/%d/%H'),
        ),
    ]
