# Generated by Django 3.2.8 on 2021-11-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to='board/image/%Y/%m/%d/%H'),
        ),
    ]
